trigger:
- '*'
pool:
  vmImage: 'windows-latest'

steps:
- task: gitmirror@0//You can install this task in marketplace
  inputs:
    GitRepoUrl: 'https://{PAT}@dev.azure.com/{ProjektMartl}/{Projekt Martl and Co. KG}/_git/{Fronted}.git'